#!/usr/bin/env python3
"""Run the mapping-folder full decompile/material-port/source-patch/recompile workflow for bhop_rose."""
from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import time
import uuid
import random
import collections
from pathlib import Path

ROOT = Path(r"C:/Code/deadlock-map-porting")
WORK = ROOT / "work" / "full_recompile_bhop_rose"
DECOMP_INNER = WORK / "decompile_inner"
DECOMP_OUTER = WORK / "decompile_outer"
CSDK = Path(r"C:/Users/User/Documents/Reduced_CSDK_12")
RC = CSDK / "game/bin_cs2/win64/resourcecompiler.exe"
DMX = CSDK / "game/bin_cs2/win64/dmxconvert.exe"
GAME = CSDK / "game/citadel"
ADDON = "bhop_rose_full_recompile"
MAP = "bhop_rose"
CONTENT_ADDON = CSDK / "content/citadel_addons" / ADDON
GAME_ADDON = CSDK / "game/citadel_addons" / ADDON
LOG_DIR = ROOT / "logs"
LOG_DIR.mkdir(exist_ok=True)

BHOP_COMMAND = (
    "sv_cheats 1; sv_enablebunnyhopping 1; sv_maxvelocity 99999; "
    "sv_staminamax 0; sv_staminalandcost 0; sv_staminajumpcost 0; "
    "sv_accelerate_use_weapon_speed 0; sv_staminarecoveryrate 60; "
    "sv_autobunnyhopping 1; sv_airaccelerate 1000; mp_roundtime 60; "
    "mp_freezetime 1; sv_falldamage_scale 0; impulse 101; "
    "sv_accelerate 255; sv_maxspeed 99999; game_mode 2; game_type 1"
)


def run(cmd: list[str], log: Path | None = None, timeout: int | None = None) -> subprocess.CompletedProcess:
    print("$", " ".join(map(str, cmd)), flush=True)
    if log:
        with log.open("w", encoding="utf-8", errors="replace") as f:
            p = subprocess.run(cmd, stdout=f, stderr=subprocess.STDOUT, text=True, timeout=timeout)
    else:
        p = subprocess.run(cmd, text=True, timeout=timeout)
    print("  rc=", p.returncode, flush=True)
    if p.returncode != 0:
        raise SystemExit(f"command failed rc={p.returncode}: {' '.join(map(str, cmd))}; see {log}")
    return p


def copytree_clean(src: Path, dst: Path):
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def _vmat_param(text: str, *names: str) -> str | None:
    for name in names:
        m = re.search(rf'"{re.escape(name)}"\s+"([^"]+)"', text)
        if m:
            return m.group(1)
    return None


def _vmat_flag(text: str, name: str) -> bool:
    return bool(re.search(rf'"{re.escape(name)}"\s+"?(?:1|true)"?', text, re.I))


def _write_sky_fallback(path: Path, text: str, reason: str) -> str:
    path.with_suffix(path.suffix + f".{reason}.bak").write_text(text, encoding="utf-8")
    path.write_text(
        f"// Rebound to CSDK sky texture for Deadlock compile compatibility ({reason})\n\n"
        '"Layer0"\n{\n\t"shader"\t"sky.vfx"\n'
        '\t"g_flBrightnessExposureBias"\t"-1"\n'
        '\t"g_flRenderOnlyExposureBias"\t"0"\n'
        '\t"SkyTexture"\t"materials/skybox/sky_dl_dusk03_exr_9dd50fb1.png"\n'
        "}\n",
        encoding="utf-8",
    )
    return "sky"


def _write_pbr(path: Path, text: str, shader: str, mode: str) -> str:
    color = _vmat_param(text, "TextureColor", "TextureLayer1Color", "g_tColor") or "materials/default/default_color.tga"
    normal = _vmat_param(text, "TextureNormal", "TextureLayer1NormalRoughness", "g_tNormal", "g_tLayer1NormalRoughness")
    self_mask = _vmat_param(text, "TextureSelfIllumMask", "g_tSelfIllumMask")
    tint = _vmat_param(text, "g_vColorTint", "g_vLayer1Tint") or "[1.000000 1.000000 1.000000 0.000000]"
    metal = _vmat_param(text, "g_flMetalness") or "0.000000"
    opacity = _vmat_param(text, "g_flOpacityScale") or "1.000000"
    self_scale = _vmat_param(text, "g_flSelfIllumScale", "g_flSelfIllumBrightness") or "1.000000"
    self_tint = _vmat_param(text, "g_vSelfIllumTint") or tint

    is_emissive = _vmat_flag(text, "F_SELF_ILLUM") or self_mask is not None or "SelfIllum" in text
    if is_emissive:
        try:
            # CS2 csgo_complex self-illum reads much hotter than Deadlock pbr at
            # scale 1.0. Boost conservatively so glowing bhop guide blocks remain
            # visibly emissive without turning the whole map into a bloom bomb.
            self_scale = f"{max(float(self_scale), 2.5):.6f}"
        except ValueError:
            self_scale = "2.500000"
    is_translucent = _vmat_flag(text, "F_TRANSLUCENT") or opacity not in ("1", "1.0", "1.00", "1.000000")
    is_glass = "glass" in shader.lower() or "glass" in path.stem.lower()

    path.with_suffix(path.suffix + f".{shader.replace('.vfx','')}.bak").write_text(text, encoding="utf-8")

    lines = [
        f"// Ported from CS2 {shader} to Deadlock pbr.vfx ({mode})",
        "// Generated by full_recompile_bhop_rose_from_mapping_recipe.py",
        "",
        '"Layer0"',
        "{",
        '\t"shader"\t"pbr.vfx"',
    ]
    if is_emissive:
        # Keep glowing CS2 materials bright/readable in Deadlock. This preserves the
        # visible emissive object; actual cast/baked light still comes from lights/VRAD.
        lines.append('\t"F_UNLIT"\t"1"')
        lines.append('\t"F_SELF_ILLUM"\t"1"')
    if is_glass:
        lines.append('\t"F_GLASS"\t"1"')
    if is_translucent and not is_glass:
        lines.append('\t"F_TRANSLUCENT"\t"1"')
    lines += [
        f'\t"TextureColor1"\t"{color}"',
        f'\t"g_vColorTint1"\t"{tint}"',
        f'\t"g_flOpacityScale1"\t"{opacity}"',
    ]
    if normal:
        lines.append(f'\t"TextureNormal1"\t"{normal}"')
    else:
        lines.append('\t"TextureNormal1"\t"materials/default/default_normal.tga"')
    if is_emissive:
        lines += [
            '\t"g_flSelfIllumAlbedoFactor1"\t"1.000000"',
            f'\t"g_flSelfIllumScale1"\t"{self_scale}"',
            f'\t"g_vSelfIllumTint1"\t"{self_tint}"',
            f'\t"TextureSelfIllumMask1"\t"{self_mask or color}"',
        ]
    if is_glass:
        lines.append(f'\t"TextureGlassMask1"\t"{self_mask or color}"')
    lines += [
        '\t"TextureRoughness1"\t"[0.350000 0.350000 0.350000 0.000000]"',
        f'\t"TextureMetalness1"\t"[{metal} {metal} {metal} 0.000000]"',
        "}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    if is_emissive:
        return "emissive_pbr"
    if is_glass:
        return "glass_pbr"
    if is_translucent:
        return "translucent_pbr"
    if normal or tint != "[1.000000 1.000000 1.000000 0.000000]" or metal not in ("0", "0.0", "0.000000"):
        return "enriched_pbr"
    return "pbr"


def rewrite_vmat(path: Path):
    text = path.read_text(errors="replace")
    shader = _vmat_param(text, "shader")
    if shader == "csgo_moondome.vfx":
        return _write_sky_fallback(path, text, "csgo_moondome")
    if shader == "sky.vfx":
        # Custom CS2 skies often decompile into split faces while the VMAT points at
        # a missing logical cubemap name. Rebind to a known compiling Deadlock sky.
        return _write_sky_fallback(path, text, "custom_sky")
    if shader and shader.startswith("csgo_"):
        if shader == "csgo_water_fancy.vfx":
            return _write_pbr(path, text, shader, "water_degraded")
        return _write_pbr(path, text, shader, "classified")
    return None


def make_texture_settings(materials_root: Path):
    for img in list(materials_root.rglob("*.png")) + list(materials_root.rglob("*.tga")) + list(materials_root.rglob("*.exr")):
        txt = img.with_suffix(".txt")
        if not txt.exists():
            txt.write_text('"settings"\n{\n}\n', encoding="utf-8")


def stage_and_rewrite_materials():
    print("[stage] cleaning addon dirs")
    if CONTENT_ADDON.exists(): shutil.rmtree(CONTENT_ADDON)
    if GAME_ADDON.exists(): shutil.rmtree(GAME_ADDON)
    (CONTENT_ADDON / "maps").mkdir(parents=True)
    GAME_ADDON.mkdir(parents=True)
    (GAME_ADDON / "addoninfo.txt").write_text('"addoninfo"\n{\n\t"IsPlayable"\t"1"\n}\n', encoding="utf-8")

    print("[stage] copy decompiled maps to content")
    shutil.copytree(DECOMP_INNER / "maps", CONTENT_ADDON / "maps", dirs_exist_ok=True)
    print("[stage] copy decompiled materials/postprocess/sounds to content")
    for sub in ["materials", "postprocess", "soundevents", "sounds"]:
        s = DECOMP_OUTER / sub
        if s.exists():
            shutil.copytree(s, CONTENT_ADDON / sub, dirs_exist_ok=True)
    mats = CONTENT_ADDON / "materials"
    # VRF may decompile cubemap sky faces as ssss_png_<hash>_ft.png etc while the VMAT
    # still refers to materials/skybox/ssss.png. Provide a concrete source image so
    # sky.vfx can compile instead of leaving the sky material unresolved.
    sky_missing = mats / "skybox" / "ssss.png"
    if not sky_missing.exists():
        faces = sorted((mats / "skybox").glob("ssss_png_*_ft.png")) + sorted((mats / "skybox").glob("ssss_png_*_up.png"))
        if faces:
            shutil.copy2(faces[0], sky_missing)
    make_texture_settings(mats)
    counts = collections.Counter()
    for vmat in mats.rglob("*.vmat"):
        kind = rewrite_vmat(vmat)
        if kind:
            counts[kind] += 1
    print("[materials] rewritten", dict(counts))


def convert_vmap_to_kv2(src: Path, dst: Path):
    run([str(DMX), "-i", str(src), "-o", str(dst), "-oe", "keyvalues2", "-of", "vmap"], log=WORK / "dmx_to_kv2.log", timeout=600)


def convert_kv2_to_vmap(src: Path, dst: Path):
    run([str(DMX), "-i", str(src), "-o", str(dst), "-oe", "binary", "-of", "vmap"], log=WORK / "dmx_to_binary.log", timeout=600)


def find_origin_near_start(text: str) -> str:
    # Prefer the existing named start teleport destination if present.
    idx = text.find('"targetname" "string" "Start"')
    if idx < 0:
        idx = text.find('"classname" "string" "info_teleport_destination"')
    if idx >= 0:
        block_start = text.rfind('"CMapEntity"', 0, idx)
        block_end = text.find('\n\t\t\t"CMapEntity"', idx)
        block = text[block_start:block_end if block_end > 0 else idx + 5000]
        m = re.search(r'"origin" "vector3" "([^"]+)"', block)
        if m:
            return m.group(1)
    return "0 0 128"


def next_node_id(text: str) -> int:
    nums = [int(x) for x in re.findall(r'"nodeID" "int" "(\d+)"', text)]
    return (max(nums) + 1000) if nums else 99000


def make_entity(classname: str, props: dict[str, str], origin: str, node_id: int, connections: str = "") -> tuple[str, str]:
    eid_top, eid_plug, eid_ep = str(uuid.uuid4()), uuid.uuid4(), uuid.uuid4()
    ref = f"0x{random.getrandbits(64):016x}"
    seed = random.randint(1, 2**31 - 1)
    prop_lines = [f'\t\t\t"classname" "string" "{classname}"']
    for k, v in props.items():
        prop_lines.append(f'\t\t\t"{k}" "string" "{v}"')
    block = f'''\n"CMapEntity"
{{
\t"id" "elementid" "{eid_top}"
\t"nodeID" "int" "{node_id}"
\t"referenceID" "uint64" "{ref}"
\t"children" "element_array" \n\t[
\t]
\t"variableTargetKeys" "string_array" \n\t[
\t]
\t"variableNames" "string_array" \n\t[
\t]
\t"relayPlugData" "DmePlugList"
\t{{
\t\t"id" "elementid" "{eid_plug}"
\t\t"names" "string_array" \n\t\t[
\t\t]
\t\t"dataTypes" "int_array" \n\t\t[
\t\t]
\t\t"plugTypes" "int_array" \n\t\t[
\t\t]
\t\t"descriptions" "string_array" \n\t\t[
\t\t]
\t}}

\t"connectionsData" "element_array" \n\t[
{connections}\t]
\t"entity_properties" "EditGameClassProps"
\t{{
\t\t"id" "elementid" "{eid_ep}"
{chr(10).join(prop_lines)}
\t}}

\t"hitNormal" "vector3" "0 0 0"
\t"isProceduralEntity" "bool" "0"
\t"origin" "vector3" "{origin}"
\t"angles" "qangle" "0 0 0"
\t"scales" "vector3" "1 1 1"
\t"nodeID" "int" "{node_id}"
\t"referenceID" "uint64" "{ref}"
\t"children" "element_array" \n\t[
\t]
\t"editorOnly" "bool" "0"
\t"force_hidden" "bool" "0"
\t"transformLocked" "bool" "0"
\t"variableTargetKeys" "string_array" \n\t[
\t]
\t"variableNames" "string_array" \n\t[
\t]
\t"customVisGroup" "string" ""
\t"randomSeed" "int" "{seed}"
}}
'''
    return eid_top, block


def make_connection() -> str:
    return f'''\t\t"DmeConnectionData"
\t\t{{
\t\t\t"id" "elementid" "{uuid.uuid4()}"
\t\t\t"outputName" "string" "OnMapSpawn"
\t\t\t"targetType" "int" "7"
\t\t\t"targetName" "string" "panel"
\t\t\t"inputName" "string" "Command"
\t\t\t"overrideParam" "string" "{BHOP_COMMAND}"
\t\t\t"delay" "float" "0"
\t\t\t"timesToFire" "int" "-1"
\t\t}}
'''


def patch_vmap_entities():
    vmap = CONTENT_ADDON / "maps" / f"{MAP}.vmap"
    kv2 = WORK / f"{MAP}.kv2.txt"
    patched = WORK / f"{MAP}.patched.kv2.txt"
    convert_vmap_to_kv2(vmap, kv2)
    text = kv2.read_text(errors="replace")

    # VRF decompile emits prop_static aggregate worldnode proxies on top of the
    # reconstructed Hammer meshes. The mapping docs explicitly call these a
    # decompile artifact (z-fighting / duplicate aggregate props). Remove the
    # static aggregate proxy, not the actual reconstructed CMapMesh geometry.
    aggregate_model = f'"model" "string" "maps/{MAP}/worldnodes/n0_lr0_c2_s_cb_mesh.vmdl"'
    pos = text.find(aggregate_model)
    if pos >= 0:
        block_start = text.rfind('\n"CMapEntity"', 0, pos)
        if block_start >= 0:
            brace = text.find('{', block_start)
            depth = 1; j = brace + 1
            while j < len(text) and depth:
                if text[j] == '{': depth += 1
                elif text[j] == '}': depth -= 1
                j += 1
            block = text[block_start:j]
            m_id = re.search(r'"id" "elementid" "([^"]+)"', block)
            if m_id:
                eid = m_id.group(1)
                text = text[:block_start] + text[j:]
                text = re.sub(r'\n\s*"element" "' + re.escape(eid) + r'",?', '', text, count=1)
                print(f"[entities] removed aggregate prop_static proxy {eid}")

    origin = find_origin_near_start(text)
    nid = next_node_id(text)
    new_entities: list[tuple[str, str]] = []
    if '"classname" "string" "point_servercommand"' not in text:
        new_entities.append(make_entity("point_servercommand", {"targetname": "panel", "vscripts": ""}, "0 0 0", nid)); nid += 1
    if '"classname" "string" "logic_auto"' not in text:
        new_entities.append(make_entity("logic_auto", {"spawnflags": "0", "vscripts": "", "targetname": "", "globalstate": ""}, "0 0 0", nid, make_connection())); nid += 1
    for team in (2, 3, 4):
        # Always add explicit Deadlock team spawns; CS2 info_player_* is not enough.
        new_entities.append(make_entity("info_team_spawn", {"grouptag": "0", "initialspawn": "0", "teamnumber": str(team), "lanenum": "6", "vscripts": "", "targetname": "", "hero_model": ""}, origin, nid)); nid += 1
    if '"targetname" "string" "stage1"' not in text:
        new_entities.append(make_entity("info_teleport_destination", {"targetname": "stage1"}, origin, nid)); nid += 1

    refs = [eid for eid, _ in new_entities]
    blocks = [block for _, block in new_entities]

    # Add element refs to CMapWorld.children (the first children array in the file).
    children_key = '"children" "element_array"'
    ck = text.find(children_key)
    arr_open = text.find('[', ck)
    arr_close = text.find('\n\t\t]', arr_open)
    if ck < 0 or arr_open < 0 or arr_close < 0:
        raise SystemExit("could not find CMapWorld children array")
    before_close = text[:arr_close].rstrip()
    sep = ",\n" if not before_close.endswith('[') else "\n"
    ref_text = sep + ",\n".join(f'\t\t\t"element" "{eid}"' for eid in refs)
    text = text[:arr_close] + ref_text + text[arr_close:]

    # Append top-level CMapEntity blocks. The element refs above point to their ids.
    new_text = text.rstrip() + "\n" + "\n".join(blocks) + "\n"
    patched.write_text(new_text, encoding="utf-8", errors="replace")
    print(f"[entities] inserted {len(blocks)} blocks / refs at origin {origin}")
    convert_kv2_to_vmap(patched, vmap)


def compile_materials():
    vmats = sorted((CONTENT_ADDON / "materials").rglob("*.vmat"))
    print(f"[compile] {len(vmats)} vmats")
    ok = 0
    for v in vmats:
        rel = v.relative_to(CONTENT_ADDON)
        log = LOG_DIR / f"compile_{ADDON}_{str(rel).replace(os.sep, '_')}.log"
        run([str(RC), "-i", str(v), "-game", str(GAME), "-nop4"], log=log, timeout=300)
        ok += 1
    print(f"[compile] material OK {ok}")


def compile_postprocess():
    vposts = sorted((CONTENT_ADDON / "postprocess").rglob("*.vpost")) if (CONTENT_ADDON / "postprocess").exists() else []
    print(f"[compile] {len(vposts)} vposts")
    for v in vposts:
        rel = v.relative_to(CONTENT_ADDON)
        log = LOG_DIR / f"compile_{ADDON}_{str(rel).replace(os.sep, '_')}.log"
        run([str(RC), "-i", str(v), "-game", str(GAME), "-nop4"], log=log, timeout=300)


def compile_models():
    vmdls = sorted((CONTENT_ADDON / "maps" / MAP).rglob("*.vmdl")) if (CONTENT_ADDON / "maps" / MAP).exists() else []
    print(f"[compile] {len(vmdls)} vmdls")
    for v in vmdls:
        rel = v.relative_to(CONTENT_ADDON)
        log = LOG_DIR / f"compile_{ADDON}_{str(rel).replace(os.sep, '_')}.log"
        run([str(RC), "-i", str(v), "-game", str(GAME), "-nop4"], log=log, timeout=300)


def compile_map():
    log = LOG_DIR / f"compile_{ADDON}_{int(time.time())}.log"
    run([sys.executable, str(ROOT / "tools/compile_with_memory_limit.py"), "--limit-gb", "28", "--", str(RC), "-i", str(CONTENT_ADDON / "maps" / f"{MAP}.vmap"), "-game", str(GAME), "-nop4"], log=log, timeout=7200)
    print(f"[compile] map log {log}")


def main():
    stage_and_rewrite_materials()
    patch_vmap_entities()
    compile_materials()
    compile_postprocess()
    compile_models()
    compile_map()
    print("DONE")
    print("game addon:", GAME_ADDON)

if __name__ == "__main__":
    main()
